#Bookly using clustering |Collabrative based

In [ ]:
import pandas as pd # type: ignore
import numpy as np # type: ignore
import matplotlib.pyplot as plt  # type: ignore
import seaborn  as sns  # type: ignore

In [4]:
books = pd.read_csv('data/Books.Csv', sep=None, encoding='latin-1')

/var/folders/x0/fxcs5xg54r51tnhxph14h1br0000gn/T/ipykernel_99704/2822024749.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  books = pd.read_csv('data/Books.Csv', sep=None, encoding='latin-1')

In [5]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [6]:
books.shape

(271360, 8)

In [7]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [8]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication','Publisher', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L']]

In [9]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [10]:
books.rename(columns={
    "ISBN":             "isbn",
    "Book-Title":       "title",
    "Book-Author":      "author",
    "Year-Of-Publication": "year",
    "Publisher":        "publisher",
    "Image-URL-S":      "img_s",
    "Image-URL-M":      "img_m",
    "Image-URL-L":      "img_l"
}, inplace=True)

In [11]:
books.head()

,isbn,title,author,year,publisher,img_s,img_m,img_l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [12]:
users=pd.read_csv('data/Users.csv',sep = None, on_bad_lines= 'skip', encoding= 'latin-1')

/var/folders/x0/fxcs5xg54r51tnhxph14h1br0000gn/T/ipykernel_99704/2189853189.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  users=pd.read_csv('data/Users.csv',sep = None, on_bad_lines= 'skip', encoding= 'latin-1')

In [13]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [14]:
users.shape

(278858, 3)

In [15]:
ratings = pd.read_csv('data/ratings.csv', sep=None, on_bad_lines='skip', encoding='latin-1')
print(ratings.columns)

/var/folders/x0/fxcs5xg54r51tnhxph14h1br0000gn/T/ipykernel_99704/2016436941.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  ratings = pd.read_csv('data/ratings.csv', sep=None, on_bad_lines='skip', encoding='latin-1')

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [16]:
ratings.head(5)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [17]:
ratings.shape

(1149780, 3)

In [18]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [19]:
ratings.rename(columns = {
    "User-ID": "user_id",
    "Book-Rating": "rating"},inplace = True)

In [20]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [21]:
ratings.rename(columns={
    "User-ID":      "user_id",
    "ISBN":         "isbn",
    "Book-Rating":  "rating"
}, inplace=True)

In [22]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [23]:
ratings['user_id'].unique().shape

(105283,)

In [24]:
x = ratings['user_id'].value_counts() > 200

In [25]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

In [26]:
x[x].shape

(899,)

In [27]:
y = x[x].index

In [28]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='user_id', length=899)

In [29]:
ratings[ratings['user_id'].isin(y)]

         user_id        isbn  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

In [30]:
ratings.head()

   user_id        isbn  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [31]:
ratings.shape

(1149780, 3)

In [32]:
books.head(2)

,isbn,title,author,year,publisher,img_s,img_m,img_l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [33]:
ratings_with_books = ratings.merge(books, on='isbn', how='inner')

In [34]:
print(ratings_with_books.head())

   user_id        isbn  rating  \
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

                                               title           author  year  \
0                               Flesh Tones: A Novel       M. J. Rose  2002
1                                   Rites of Passage       Judith Rae  2001
2                                       The Notebook  Nicholas Sparks  1996
3                                     Help!: Level 1    Philip Prowse  1999
4  The Amsterdam Connection : Level 4 (Cambridge ...      Sue Leather  2001

                    publisher  \
0            Ballantine Books
1                      Heinle
2                Warner Books
3  Cambridge University Press
4  Cambridge University Press

                                               img_s  \
0  http://images.amazon.com/images/P/034545104X.0...
1  http://images.amazon.com/images/P/0155061224.0...
2  http://images.amazon.com/images/P/0446520802.0...
3  http://images.amazon.com/images/P/052165615X.0...
4  http://images.amazon.com/images/P/0521795028.0...

                                               img_m  \
0  http://images.amazon.com/images/P/034545104X.0...
1  http://images.amazon.com/images/P/0155061224.0...
2  http://images.amazon.com/images/P/0446520802.0...
3  http://images.amazon.com/images/P/052165615X.0...
4  http://images.amazon.com/images/P/0521795028.0...

                                               img_l
0  http://images.amazon.com/images/P/034545104X.0...
1  http://images.amazon.com/images/P/0155061224.0...
2  http://images.amazon.com/images/P/0446520802.0...
3  http://images.amazon.com/images/P/052165615X.0...
4  http://images.amazon.com/images/P/0521795028.0...

In [35]:
ratings_with_books.shape

(1031136, 10)

In [36]:
num_ratings= ratings_with_books.groupby('title')['rating'].count().reset_index()

In [37]:
num_ratings.head ()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       4
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Ask Lily (Young Women of Faith: Lily Series, ...       1
4   Beyond IBM: Leadership Marketing and Finance ...       1

num_ratings.rename(columns={'rating': 'num_of_rating'}, inplace=True)

In [58]:
num_ratings.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       4
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Ask Lily (Young Women of Faith: Lily Series, ...       1
4   Beyond IBM: Leadership Marketing and Finance ...       1

In [59]:
ratings_with_books.head()

,user_id,isbn,rating,title,author,year,publisher,img_s,img_m,img_l
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [60]:
final_rating=ratings_with_books.merge(num_ratings, on= 'title')

In [61]:
final_rating.head(2)

,user_id,isbn,rating_x,title,author,year,publisher,img_s,img_m,img_l,rating_y
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,60
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,14

In [62]:
final_rating.shape

(1031136, 11)

In [63]:
final_rating[final_rating['rating_y']>=50]

,user_id,isbn,rating_x,title,author,year,publisher,img_s,img_m,img_l,rating_y
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,60
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,650
6,276744,038550120X,7,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,838
7,276746,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,274
8,276746,0449006522,0,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...,111
...,...,...,...,...,...,...,...,...,...,...,...
1031123,276704,0441007813,0,Obsidian Butterfly,Laurell K. Hamilton,2000,Ace Books,http://images.amazon.com/images/P/0441007813.0...,http://images.amazon.com/images/P/0441007813.0...,http://images.amazon.com/images/P/0441007813.0...,53
1031124,276704,0446353957,0,Mirror Image,Sandra Brown,1990,Warner Books,http://images.amazon.com/images/P/0446353957.0...,http://images.amazon.com/images/P/0446353957.0...,http://images.amazon.com/images/P/0446353957.0...,159
1031125,276704,0446605409,0,Plum Island,Nelson DeMille,1998,Warner Books,http://images.amazon.com/images/P/0446605409.0...,http://images.amazon.com/images/P/0446605409.0...,http://images.amazon.com/images/P/0446605409.0...,150
1031128,276704,0743211383,7,Dreamcatcher,Stephen King,2001,Scribner,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...,http://images.amazon.com/images/P/0743211383.0...,481
1031129,276704,080410526X,0,All I Really Need to Know,ROBERT FULGHUM,1989,Ivy Books,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...,258

In [64]:
final_rating.sample(10)

,user_id,isbn,rating_x,title,author,year,publisher,img_s,img_m,img_l,rating_y
233897,60244,0807508527,7,"The Boxcar Children (Boxcar Children, No 1)",Gertrude Chandler Warner,1989,Albert Whitman &amp; Company,http://images.amazon.com/images/P/0807508527.0...,http://images.amazon.com/images/P/0807508527.0...,http://images.amazon.com/images/P/0807508527.0...,33
969204,258270,0380731851,0,Mystic River,Dennis Lehane,2002,HarperTorch,http://images.amazon.com/images/P/0380731851.0...,http://images.amazon.com/images/P/0380731851.0...,http://images.amazon.com/images/P/0380731851.0...,362
1020340,273767,0590478044,6,"Midnight Phone Calls (Clue Books, No 5)",A.E. Parker,1994,Scholastic Paperbacks (Mm),http://images.amazon.com/images/P/0590478044.0...,http://images.amazon.com/images/P/0590478044.0...,http://images.amazon.com/images/P/0590478044.0...,4
910859,243294,0440221595,8,The Glass Lake,Maeve Binchy,1996,Dell,http://images.amazon.com/images/P/0440221595.0...,http://images.amazon.com/images/P/0440221595.0...,http://images.amazon.com/images/P/0440221595.0...,158
755940,204822,0345384466,5,The Witching Hour (Lives of the Mayfair Witches),ANNE RICE,1993,Ballantine Books,http://images.amazon.com/images/P/0345384466.0...,http://images.amazon.com/images/P/0345384466.0...,http://images.amazon.com/images/P/0345384466.0...,274
544046,146564,1932360085,8,How to Get Stupid White Men Out of Office: The...,Adrienne M. Brown,2004,Soft Skull Press,http://images.amazon.com/images/P/1932360085.0...,http://images.amazon.com/images/P/1932360085.0...,http://images.amazon.com/images/P/1932360085.0...,6
836192,226545,1551668831,0,Orphan,Stella Cameron,2002,Mira,http://images.amazon.com/images/P/1551668831.0...,http://images.amazon.com/images/P/1551668831.0...,http://images.amazon.com/images/P/1551668831.0...,22
442438,118434,0864170106,0,By My Own Authority,Marian Pretzel,1985,Intl Specialized Book Service,http://images.amazon.com/images/P/0864170106.0...,http://images.amazon.com/images/P/0864170106.0...,http://images.amazon.com/images/P/0864170106.0...,1
46471,11676,0671742760,0,DRAGON,Clive Cussler,1991,Pocket,http://images.amazon.com/images/P/0671742760.0...,http://images.amazon.com/images/P/0671742760.0...,http://images.amazon.com/images/P/0671742760.0...,49
990445,265115,0425187144,8,"Hanging by a Thread (Ferris, Monica. Needlecra...",Monica Ferris,2003,Prime Crime,http://images.amazon.com/images/P/0425187144.0...,http://images.amazon.com/images/P/0425187144.0...,http://images.amazon.com/images/P/0425187144.0...,30

In [65]:
final_rating.shape

(1031136, 11)

In [66]:
final_rating.drop_duplicates(['user_id', 'title'], inplace=True)

In [67]:
final_rating.shape

(1026358, 11)

In [68]:
final_rating

,user_id,isbn,rating_x,title,author,year,publisher,img_s,img_m,img_l,rating_y
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,60
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,14
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,650
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,1
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,1
...,...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,3
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,3
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,40
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,44
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,15

In [69]:
user_counts = final_rating['user_id'].value_counts()
filtered_users = user_counts[user_counts > 200].index

In [70]:
book_counts = final_rating['title'].value_counts()
filtered_books = book_counts[book_counts > 100].index

In [71]:
filtered_data = final_rating[
    (final_rating['user_id'].isin(filtered_users)) &
    (final_rating['title'].isin(filtered_books))
]

In [87]:
book_pivot = filtered_data.pivot_table(index='title', columns='user_id', values='rating_x').fillna(0)

In [88]:
book_pivot.head()

user_id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
book_pivot.shape

(890, 805)

In [90]:
book_pivot.fillna(0, inplace= True)

In [91]:
book_pivot

user_id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from scipy.sparse import csr_matrix # type: ignore

In [93]:
book_sparse = csr_matrix(book_pivot)

In [94]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15811 stored elements and shape (890, 805)>

In [ ]:
from sklearn.neighbors import NearestNeighbors # type: ignore
model = NearestNeighbors(metric='cosine',algorithm='brute')

In [99]:
model.fit(book_pivot.values)

NearestNeighbors(algorithm='brute', metric='cosine')

In [147]:
distance, suggestion = model.kneighbors(book_pivot.iloc[276,:].values.reshape(1,-1),n_neighbors = 6)

In [148]:
distance

array([[0.        , 0.39727322, 0.42831546, 0.51804943, 0.55457253,
        0.64629251]])

In [149]:
suggestion

array([[276, 279, 277, 281, 280, 278]])

In [150]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))',
       'Harry Potter and the Sorcerer's Stone (Book 1)',
       'Harry Potter and the Order of the Phoenix (Book 5)'],
      dtype='object', name='title')

In [151]:
book_pivot.index[276]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [152]:
book_pivot.index

Index(['1984', '1st to Die: A Novel', '24 Hours', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road',
       'A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       ...
       'Without Remorse', 'Wizard and Glass (The Dark Tower, Book 4)',
       'Women Who Run with the Wolves',
       'Word Freak: Heartbreak, Triumph, Genius, and Obsession in the World of Competitive Scrabble Players',
       'Wuthering Heights', 'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=890)

In [153]:
books_name = book_pivot.index

In [154]:
import pickle
pickle.dump(model, open('artifacts/model.pkl', 'wb'))
pickle.dump(books_name, open('artifacts/books_name.pkl', 'wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl', 'wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl', 'wb'))

In [157]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors = 6)

    for i in range(len(suggestion)):
      books = book_pivot.index[suggestion[i]]  
    for j in books:
        print(j)

In [158]:
book_name = 'Harry Potter and the Chamber of Secrets (Book 2)'
recommend_book(book_name)

Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
Harry Potter and the Sorcerer's Stone (Book 1)
Harry Potter and the Order of the Phoenix (Book 5)